### ISSUE TITLE
Issue with Guide/system time android (Nvidia Shield)

### ISSUE THREAD

**Issue by dhallam56** [kodi-pvr/pvr.vbox#215] opened 2018-08-13 19:37 UTC
I have noticed for a while now, but just not had time to follow up, as the issues is my guide + system time in kodi is always and hour behind.

I am running two Nvidia Shield units and both have the same issue.
The time in android is correct and if you don't have the Vbox addon enabled the time in kodi is still correct.
If I enable the addon when entering kodi the time is correct momentarily until it syncs the guide then the time goes back an hour.
Also when entering the guide everything is an hour behind, but the programs are somehow correct.

Like if the current time is 6pm the guide states its 5pm but the program in the guide is current program.

I have checked the Vbox and its the correct time set from the live signal and is currently GMT+01:00 which is correct.
I have had the issue in kodi 17.6 and now I am running kodi 18 nightly for the Oreo fixes to the addon.

Any info on what needs tweaking would be perfect.

Keep up the good work

**Comment by phunkyfish** [comment] 2019-10-19 18:47
Is this still an issue?

**Comment by phunkyfish** [comment] 2019-10-19 19:07
I remember something like this and setting the interface regional settings resolved it. I think.

**Comment by robjrowe** [comment] 2019-10-21 09:42
Yes I can confirm it is an issue for me too.  I'm using your new 4.50 test build (so grateful that the timeshift issue is fixed!) - if we could get to the bottom of the crazy timezone issues I think I'll finally get to a setup that my wife won't complain about!

**Comment by Jalle19** [comment] 2019-10-21 10:00
I think if the system time in Kodi is wrong then it's not an addon issue but a Kodi issue?

**Comment by robjrowe** [comment] 2019-10-21 10:33
I don't think so, if I disable the pvr addon, the system time is correct (GMT+1 in my case).  

If I enable the addon then the clock on the kodi home screen starts off correct for a couple of seconds until the pvr starts to load.  During this time the clock is hidden as the pvr channel/guide/timers loading status is on top, but as soon as that is finished, the clock reappears showing 1hr earlier (GMT).  Sometimes on one of my 2 TVs you can watch the hour text flicker between two hour values as if two processes are fighting,  it is bizarre!

Similar to how the OP stated, the tv guide shows the 'current time line' as being the new wrong kodi time (GMT), but the TV programs listed as in progress are correctly aligned to what is actually being broadcast right now (GMT+1).  Difficult to describe I know!

**Comment by phunkyfish** [comment] 2019-10-21 10:45
I think this is due the gmtime workaround and time zone setting. 

If I create a reminder it will always be +1 hours. Which means there is a calc off somewhere.

Now that I have a working vbox I can look at this but as the change I expect is substantial will probably do on matrix version.

**Comment by phunkyfish** [comment] 2019-10-21 11:15
@robjrowe if I try a fix for this on the matrix version of the addon can you test it?

If it turn out to be an easy fix I can backport it.

**Comment by robjrowe** [comment] 2019-10-21 11:27
I don't currently have  Matrix setup, but don't mind switching one TV over so long as it is reasonably functional (I have no idea how far the through v19 development is).

My current setup isn't too complicated to reinstall/revert back so will give it a go and see how it goes.  Do you think I should just take the latest nightly or is there 
a 'good' one?  It is ARMv7 if you need to know.

**Comment by dhallam56** [comment] 2019-10-21 11:30
Im Currentally on Matrix nightly from 27th September. I have to use this one an later ones breaks my emby server addon. :-(

**Comment by phunkyfish** [comment] 2019-10-21 11:36
Just pick one from before October 14th and it should do for testing purposes.

**Comment by phunkyfish** [comment] 2019-10-21 11:37
I can’t reproduce this issue so I need someone to test it.

**Comment by robjrowe** [comment] 2019-10-21 12:14
I'll install a 19 build and confirm when I've got it to reproduce the issue

**Comment by robjrowe** [comment] 2019-10-21 13:06
Ok, so I've done an install of the 13-Oct nightly and enabled the 5.2 addon.  I can confirm that the problem is present, although it seems subtly different to before.

It still does the thing where the kodi clock time gets changed after the pvr addon starts up, and the tv guide still has the current-time line set at the point that Kodi thinks is the time (but it is wrong) - the difference now is that the guide timeline across the top and the programme data line up with the published show times (you remember in my earlier description I said that the guide showed programmes that had their times shifted)

**Comment by robjrowe** [comment] 2019-10-21 13:15
Also worth pointing out that now that I think about it, this may related to daylight saving time - we are currently in British Summer Time (+1), which ends next Sunday, after which it wouldn't surprise me if this issue goes "underground" for another 6 months

**Comment by phunkyfish** [comment] 2019-10-21 13:31
The I had better fix it soon 😉

**Comment by phunkyfish** [comment] 2019-10-21 13:34
And your EPG is loaded from the vbox correct?

**Comment by dhallam56** [comment] 2019-10-21 13:35
Yes the issues does get resolved when summertime +1 is removed

**Comment by robjrowe** [comment] 2019-10-21 13:36
Correct, the guide data is OTA, neither kodi nor vbox itself are set to use an external data source

**Comment by phunkyfish** [comment] 2019-10-21 13:44
Perfect. Same setup as mine.

**Comment by phunkyfish** [comment] 2019-10-21 15:38
@robjrowe if you can test the ARM7 zip from here: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-226/1/artifacts

We can see if my first theory is correct.

**Comment by robjrowe** [comment] 2019-10-21 15:59
Looks pretty good at first check - just seeing if I can break it ;)

**Comment by robjrowe** [comment] 2019-10-21 16:05
Well it looks like you've gone and fixed it straight away - excellent work!

What was the problem?

**Comment by phunkyfish** [comment] 2019-10-21 16:12
Flipping timezones to parse timestamps due to unsupported standard libraries on android. Used a different method to avoid that problem.

**Comment by robjrowe** [comment] 2019-10-21 16:20
Would it be easy to port it back onto the 4.50 code?

**Comment by phunkyfish** [comment] 2019-10-21 16:27
It should be too hard.

**Comment by phunkyfish** [comment] 2019-10-21 16:28
I will send you a new Matrix test build later to test again. Once that’s ok will try a Leia build.

**Comment by phunkyfish** [comment] 2019-10-21 16:57
Ok, can you try this build: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-226/3/artifacts

I removed all the android compatibility functions (they should no longer be required) in case they cause issues. I also removed the external xmltv from the addon.

**Comment by phunkyfish** [comment] 2019-10-21 17:00
Hold on, I forgot to increase the version number. Will supply new build shortly.

**Comment by phunkyfish** [comment] 2019-10-21 17:04
These builds: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.vbox/detail/PR-226/4/artifacts

**Comment by phunkyfish** [comment] 2019-10-21 17:17
Assuming these work will then try to port to Leia.

**Comment by dhallam56** [comment] 2019-10-21 17:42
Hi im running the 5.4.0 on matrix and its spot on working as expected. downloaded tonight at 6.

Only thing frontroom running leia errors on install, but not to worry ill update to Matrix same version as other box as thats running fine.

Your a lifesaver

**Comment by phunkyfish** [comment] 2019-10-21 17:47
For Leia try updating the repo from the left nav before trying to install.

**Comment by robjrowe** [comment] 2019-10-21 17:51
Looks good to me!  I tried guide, recordings playback etc, all seems to be working well ( and the clock is finally right!!!).

Well done and thanks very much!

**Comment by phunkyfish** [comment] 2019-10-21 18:03
@robjrowe it will be interesting to see what happens when the clocks change next week ;) At least we don't need to wait long to test it ;)

**Comment by dhallam56** [comment] 2019-10-21 18:05
> 
> 
> For Leia try updating the repo from the left nav before trying to install.

That worked fine, i was upgrading from the Zip i downloaded onto my Server.

All fixed now

**Comment by phunkyfish** [comment] 2019-10-21 18:07
Fixed by:
https://github.com/kodi-pvr/pvr.vbox/pull/226
https://github.com/kodi-pvr/pvr.vbox/pull/227

**Comment by robjrowe** [comment] 2019-10-21 18:38
Amazing, thanks - the lounge TV is currently 'occupied'.... so I'll test that out tomorrow :)

**Comment by robjrowe** [comment] 2019-10-22 12:18
Leia build 4.6 works as expected  :)

Many thanks

**Comment by phunkyfish** [comment] 2019-10-22 22:07
Cool, released.

**Closed by phunkyfish** 2019-10-22 22:07 UTC
