### ISSUE TITLE
buffer.ts growing to fill disk size in LibreElec 7.95.3

### ISSUE THREAD

**Issue by phunkyfish** [kodi-pvr/pvr.vbox#183] opened 2017-02-23 06:46 UTC
I only noticed this as I was trying to upgrade as there was no space to copy any files to the device.

Timesift is enabled. I will check again in 8.0.0 once I upgrade.

**Comment by Jalle19** [comment] 2017-02-23 06:49
This is practically a duplicate of https://github.com/kodi-pvr/pvr.vbox/issues/35

**Closed by Jalle19** 2017-02-23 06:49 UTC
