### ISSUE TITLE
Kodi live tv hangs

### ISSUE THREAD

**Issue by loganx50** [kodi-pvr/pvr.vbox#104] opened 2015-09-27 09:05 UTC
http://xbmclogs.com/phkmqrwsc

**Comment by Jalle19** [comment] 2015-09-27 22:03
Can you give me some more details on when and how it hangs?

**Comment by loganx50** [comment] 2015-09-28 08:48
sure, sorry. more detail here http://forum.kodi.tv/showthread.php?tid=236666

have found this on raspberry pi as well as amazon fire tv

let me know if you need debug level

**Comment by Jalle19** [comment] 2015-09-28 09:07
I found a bug which may have been the cause of all the various hangs people have experienced. It's not merged yet but it will be available once Kodi 15.2 is released.

**Comment by falcon03** [comment] 2015-09-29 08:07
Hi,

I experience some hangs as well. Let's suppose that I keep watching to a channel for a few hours. If I stop watching the channel and try to play another one, Kodi hangs showing the busy-dialog until the timeout expires. If I quit Kodi and then start it again, it won't see the VBox TV Gateway at all, but it won't show errors about not being able to connect to it as well. The only solution for me is to restart the VBox TV Gateway and then disable/reenable live tv support in kodi's system settings.

I am running Kodi 15.1 under Mac OS X 10.11 with timeshift support enabled. Do you think my issue is related to the bug you fixed? If so, I'd be happy to test Kodi 15.2 rc1; if not, I'd be happy to open another issue with debug logs...

**Comment by falcon03** [comment] 2015-09-29 08:11
just want to add that if I keep watching to a channel for just a few minutes everything works perfectly. The firmware on my VBox is version 2.50 and I've turned on the setting to try to wake up remote origin servers in Kodi's settings.

**Comment by loganx50** [comment] 2015-09-29 09:47
I didn't know there was a firmware version 2.50. I have XTI_VB.2.48

**Comment by falcon03** [comment] 2015-10-01 15:04
You're right, firmware version is 2.48. I got confused with another device.

Anyways, I've noticed that when the problem happens if I click on the "streaming" link in the vbox web interface I get an error saying something like "Error 351, streamer proxy does not respond". What could be causing the problem? Could 15.2 RC2 fix it?

**Comment by Jalle19** [comment] 2015-10-01 15:10
Probably not, that sounds like an issue with the VBox itself.

**Comment by Jalle19** [comment] 2016-09-26 15:36
This shouldn't be a problem anymore with Kodi Krypton.

**Closed by Jalle19** 2016-09-26 15:36 UTC
